// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class HelpTable : CsvTable
{
	public class Row
	{
		public string title{get;set;}
		public string information{get;set;}
        public Row() { }
        public Row(string title,string information) {
            this.title = title;
            this.information = information;
        }
    }

	List<Row> rowList = new List<Row>();

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public override void Load(string csvData)
	{
		rowList.Clear();
		string[][] grid = ParserCSV.Parse(csvData);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.title = grid[i][0];
			row.information = grid[i][1];

			rowList.Add(row);
		}
		isLoaded = true;
	}
    public override string UnLoad()
    {
        for (int i = 1; i < rowList.Count; i++)
        {
            Row row = rowList[i-1];
			grid[i][0] = row.title;
			grid[i][1] = row.information;

        }
       return UParserCSV.UParser(grid);
    }

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_title(string find)
	{
		return rowList.Find(x => x.title == find);
	}
	public List<Row> FindAll_title(string find)
	{
		return rowList.FindAll(x => x.title == find);
	}
	public Row Find_information(string find)
	{
		return rowList.Find(x => x.information == find);
	}
	public List<Row> FindAll_information(string find)
	{
		return rowList.FindAll(x => x.information == find);
	}

}